name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'examples/**'
      - 'lib/**'
      - 'hw/**'
      - 'tools/get_deps.py'
      - 'tools/build.py'
      - '.github/actions/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/build_util.yml'
      - '.github/workflows/ci_set_matrix.py'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.set-matrix-json.outputs.matrix }}
    steps:
      - name: Checkout TinyUSB
        uses: actions/checkout@v4

      - name: Generate matrix json
        id: set-matrix-json
        run: |
          MATRIX_JSON=$(python .github/workflows/ci_set_matrix.py)
          echo "matrix=$MATRIX_JSON"
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  # ---------------------------------------
  # Build CMake
  # ---------------------------------------
  cmake:
    needs: set-matrix
    uses: ./.github/workflows/build_util.yml
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          # - 'arm-clang' is built by circle-ci in PR
          - 'aarch64-gcc'
          - 'arm-gcc'
          - 'msp430-gcc'
          - 'riscv-gcc'
    with:
      build-system: 'cmake'
      toolchain: ${{ matrix.toolchain }}
      build-args: ${{ toJSON(fromJSON(needs.set-matrix.outputs.json)[matrix.toolchain]) }}
      one-per-family: ${{ github.event_name == 'push' }}

  # ---------------------------------------
  # Build Make (built by circle-ci in PR, only build on push here)
  # ---------------------------------------
  make:
    if: github.event_name == 'push'
    needs: set-matrix
    uses: ./.github/workflows/build_util.yml
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          # 'arm-clang'
          - 'arm-gcc'
          - 'aarch64-gcc'
          - 'msp430-gcc'
          - 'riscv-gcc'
          - 'rx-gcc'
          - 'esp-idf' # build-system is ignored
    with:
      build-system: 'make'
      toolchain: ${{ matrix.toolchain }}
      build-args: ${{ toJSON(fromJSON(needs.set-matrix.outputs.json)[matrix.toolchain]) }}
      one-per-family: true
